### ISSUE TITLE
update jupyter notebook image 

### ISSUE THREAD

**Issue by rafadavis** [DHRI-Curriculum/text-analysis#22]
In overview.md, image shows older version of jupyter notebook (version 5.4.0 to 6.0.3)

**Comment by gofilipa** [comment]
Hi @rafadavis, just downloaded Anaconda again for OSX (actually needed to do it, because there was something wrong with launching my previous installation). Below are the up to date images for the conda dashboard and jupyter notebook:

![image](https://user-images.githubusercontent.com/14188724/87670383-8713c480-c767-11ea-863e-60b2385b65c0.png)

![image](https://user-images.githubusercontent.com/14188724/87670430-9b57c180-c767-11ea-873a-6402e3c64636.png)
