### ISSUE TITLE
Add option to run nltk.download() in command line instead of GUI?

### ISSUE THREAD

**Issue by rafadavis** [DHRI-Curriculum/text-analysis#27]
Section overview.md
Last DRI some macs had this weird bug. Whenever they tried to run nltk.download(), it would log them out of the computer. I don't know if that is still happening, though.
The work around was a bit more complicated, since they just had to run nltk.download_shell() , and choose the options from the terminal, which was not super intuitive.

**Comment by lmrhody** [comment]
the problem you're describing is a specific problem with OS Catalina. there are a couple of work arounds on stackoverflow and in the Mac user forums. 

Perhaps @kallewesterling we need some styling for a "warning" or "known issue" in a lesson.

**Comment by gofilipa** [comment]
Found the relevant issue descriptions from the [NLTK repo](https://github.com/nltk/nltk/issues/2357) and a couple from stack overflow:

- https://stackoverflow.com/questions/16598830/nltk-download-hangs-on-os-x
- https://stackoverflow.com/questions/59755744/nltk-data-download-hangs-on-macos-in-anaconda-environment

I tried replicating the error with my fresh installation of conda but I had no issues downloading NLTK, probably because I'm running on OS Mojave (not Catalina). 

Like @rafadavis said, it seems that we might have to provide a shell option, even if it's not very intuitive.

**Comment by rachelrakov** [comment]
Let me know if you guys need help with this 💖

**Comment by gofilipa** [comment]
Update! Turns out I didn't have NLTK properly installed and ended up getting the same error on nltk.download() which logged me out of my computer. Even though I don't have Catalina, I still got this same error!

The good news is that I took images of my NLTK download, which we can add to the workshop in case other people have trouble. The first image is just what my jupyter screen looks like after downloading `nltk.download_shell()`. The second includes red boxes where I entered information to download the nltk_data folder. After downloading, the data folder appears immediately in my root directory. 

![image](https://user-images.githubusercontent.com/14188724/87680444-59ce1300-c775-11ea-93a3-809f4b1c3800.png)

![image](https://user-images.githubusercontent.com/14188724/87680789-c47f4e80-c775-11ea-94f3-65814a7cea79.png)

**Comment by rafadavis** [comment]
Thanks, @gofilipa! Images properly saved.
@kallewesterling , how are we gonna proceed with the "warnings/compatibility issues"?

**Comment by gofilipa** [comment]
forgot to add the final image of the series, the last step where the user "quits" the NLTK downloader:
![image](https://user-images.githubusercontent.com/14188724/87812686-7abb6480-c858-11ea-8b45-23aa6dcddbe7.png)

**Comment by kallewesterling** [comment]
@rafadavis It's something that we have discussed as having part of the `meta.md` file that we should create, perhaps in the next sprint, for each of the workshops, see more here: https://github.com/DHRI-Curriculum/project-lab/issues/17

**Comment by kallewesterling** [comment]
Here, you can see [an example of what a `meta.md` file would look like](https://github.com/DHRI-Curriculum/project-lab/blob/v2.0-kalle-testing-lessons/meta.md).

**Comment by rafadavis** [comment]
Cool. I'll just close this issue for now, and we can come back to it later.
Also, at some point we should discuss how we will deal with installations. Part of this workshop could go to an installation section.

**Comment by kallewesterling** [comment]
Yup, I think installations might need to be a whole other thing... I should open a `django-app` issue about that as well!

**Comment by kallewesterling** [comment]
(See https://github.com/DHRI-Curriculum/project-lab/issues/26)
