### ISSUE TITLE
lessons.md reviewed

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/text-analysis#33]
- Look at your workshop on [the website](http://kallewesterling.pythonanywhere.com) to see what your workshop currently looks like, and what looks like it needs to change.
- Think about order and transitions—do the lessons follow a logical pattern and is it working? Do you need to add something somewhere? Are the transitions between the lessons clear?
- Can you add a challenge at the end of the lesson that summarizes what the learner has learned, and activates the knowledge in an interactive way.
- Think about the length of the lessons — are they too long? Too short? In general, each lesson should cover one topic, or one particular skill — or perhaps connect two skills. If you find that you’re covering more than that in one lesson, perhaps they should be split into more than one.
- While reviewing the lessons.md file, think about vocabulary terms that we should add in an easily accessible "dictionary" for our learners.

Feel free to reach out to me and @lmrhody and ask for help, if you need it. Also feel free to involve others in the group!

**Comment by kallewesterling** [comment]
If you want another view of the Markdown and how it is being translated/parsed into the website, you can see [this link](https://kallewesterling.pythonanywhere.com/preview). It is a new tool that I created that will download the live markdown from GitHub and preview the way that the website interprets the markdown. In order to access it, you'll have to be logged in using `admin` as your login and `admin` as your password!

Once you're logged in, you can click "Preview in parser" and it should show you what the live markdown is, and how the website will interpret your markdown.

**Comment by gofilipa** [comment]
Hi Kalle, I'm having trouble logging into both the pythonanywhere admin. I'm using the username `admin` with password `admin`. Am I doing something wrong?

**Comment by kallewesterling** [comment]
Hmmm it should work. Can you try again?

**Comment by gofilipa** [comment]
Yes it works now!

**Comment by hackettka** [comment]
Rafa, this lesson looks great! Here are a few suggestions I have after reviewing it: 

- In the first sentence of the abstract I might make it "...analyze that text faster than humanly possible" or something that points to this specific type of text analysis, because it reads as though, NOW we can do this -- but text has always been analyzable and lots of people do analyze texts without computers.. 
- Bullet 5 of the lesson objectives - i might add the qualifier - "computer-based" languages just for clarification. 
- In the Overview, you might want to link to the Python workshop. I think Kalle said he is going to adjust the link so you can link to the github repo as a proxy. 
- Lesson #2 like in the beginning, i think you could refine a little. It reads as though text is a new form of data now, but its not, we just have new tools that help us break into it in different ways.
- Lesson #4 GitHub repo you mention could be linked to. Again, I think Kalle is working with those URLs when he ingests the content. 
- Lesson #4You mention a URL to put into Firefox and Google Chrome, but its not clear to me as the reader what URL you mean.
- Lesson #4 I think maybe some screenshots could help the reader "find the notebook file and open it" or start a New Python3 Notebook. 
- You use : %matplotlib inline -- is that a percentage sign? If not, maybe you want to clarify how to get that symbol? 
- Lesson #4 I would clarify more that "nothing happens" means you did it correctly. Maybe add that this isn't always the case, as we'll see later in the lesson. It might also be useful to note somewhere what it looks like when an error occurs. This is something that we should discuss more as a group more as it may be an issue for all of us... I don't have anything in the Git/GitHub workshop - and I'm not sure I could even anticipate the problems - but maybe we want a general statement about what to do when you hit a snag - i.e. STACKOVERFLOOOOWWW! :)
- Lesson #6 you tell the reader to go find text 2 - maybe remind them about where and how? You could even turn it into a challenge with a hidden solution. 
- Lesson #7 Are you referring to python functions built into Jupyter Notebook? Maybe clarify? 
- Lesson #7 should that challenge have a solution? 
- Lesson #9 maybe emphasize "url method" in some way. I think you do this otherwise throughout.
- Lesson #10 maybe the first time you use POS tagging in the paragraph, say part-of-speech (POS) tagging in case people don't make the connection between the title and this acronym. 

Throughout 
- I suggest blocking the text more so discrete ideas are one paragraph. For example, in Lesson #2 - you could start a new paragraph after "Let's say..." and another after "There has been...". In Lesson #4, "In the first blank cell" could be a new line. I think this helps with clarity, but its also a starting point for thinking about accessibility on the web. 
- It's not always clear to me why some text is block-quoted, like in lesson #2. There specifically, it seems like some could be block-quoted, but the 2nd half maybe not.. ? 
- There are a lot of times when I as the reader was not sure if I would be adding a command into the same cell or a new cell. This could be clarified throughout. And/or - in lesson #4 it was helpful to see the image with all 3 commands in the same cell, but I was confused before I got there. Maybe move that up and use it to prepare the reader for the lesson? 
- Relatedly, maybe somewhere there should be an explanation of when things go in one cell and when they go in multiple cells. 
- I also remember there being a lot discussed in the workshop about how the cells interact with each other. A lot of this is missing, but seems important for a new user to know. Maybe we can point them to a resource if we don't want to recreate that info.

**Comment by kallewesterling** [comment]
@hackettka is correct - feel free to link however you see fit. I will say that the more absolute links the better - that is, try to stay away from `../` and `./` as much as possible. If you need to link to a GitHub repository, write out `https://github.com/DHRI-Curriculum/python/` or whatever it is that you want to link to. It will make it easier for me to do it programmatically later on, and still maintain functionality here on GitHub.

**Comment by rafadavis** [comment]
Hey @hackettka ! Thanks so much for such a detailed reading. I'm already working on some of the changes you suggested. 
However, I think the links you used might have some problem, because they are not leading me to sections of text. Can you please double check that? I'm having some trouble finding the parts of the workshop they relate to.
Sorry to bring you more work. :)

**Comment by hackettka** [comment]
Hi @rafadavis - no, they don't link, that was something GitHub did. The numbers correspond to the numbers on the site Kalle is building. So if you go to Lesson 2 on that site, you'll see my comments apply to that section. Sorry for the confusion!

**Comment by kallewesterling** [comment]
@rafadavis  I went ahead and closed out this issue since it pertained to `sprint 3` (with finalization in `sprint 4`). If there are unresolved issues in here, feel free to reopen, but I'm doing my cleaning-up of our progress.
