### ISSUE TITLE
The issue that closes them all

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/text-analysis#49]
Feel free to close this issue after you have pushed all of your local branch updates to your GitHub repo, so I can initiate a pull request to the `v2.0` branch. (If you feel comfortable and interested in doing it yourself, you can do that as well, of course!)

This is the issue that closes out the v2.0 edits from you. Thank you so very much for all your hard work this summer!

**Comment by rafadavis** [comment]
While reviewing everything, I realized I never finished my assessments.md file. Since we decided to have assessment questions per page in the workshop, do we still have to do it, or this file will no longer be necessary? Should I copy all the assessment questions of the workshop to this file?
Sorry for the confusion.

Other than that, everything is up to date, so we can do the pull request.

**Comment by kallewesterling** [comment]
No need for apologies. `assessment.md` was an early idea that never really came to fruition. You can leave it alone for now, and we'll see if we get back to it later in the development process! Thank you!
